apiVersion: tekton.dev/v1beta1

kind: TaskRun

metadata:
  name: mail-taskrun
spec:
  params:
  - name: server
    value: server-secret
  - name: subject
    value: Hi, again!
  - name: body
    value: "Tekton email"
  - name: sender
    value: "kdshapka@gmail.com"
  - name: recipients
    value: "kdshapka@gmail.com"
  taskRef:
    name: sendmail