apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: curl-pipeline-run-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: curl-pipeline
  params:
    - name: url-secret
      value: rocketchat-url
    - name: options
      value:
        - "-X"
        - "POST"
        - "-H"
        - "Content-Type: application/json"
        - "--data"
        - |-
          {
            "text": "Automated Alert",
            "attachments": [
              {
                "title": "A very thoughtful title",
                "text": "Some intriguing text.",
                "color": "#764FA5"
              }
            ]
          }
