apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: send-message-pipeline
  namespace: c345c5-tools
spec:
  params:
    - description: The name of the secret holding the Rocket.Chat URL
      name: rocketchat-url-secret
      type: string
  tasks:
    - name: generate-message
      taskRef:
        kind: Task
        name: generate-message
    - name: send-to-rocketchat
      params:
        - name: url-secret
          value: $(params.rocketchat-url-secret)
        - name: options
          value:
            - '-X'
            - POST
            - '-H'
            - 'Content-Type: application/json'
            - '--data'
            - $(tasks.generate-message.results.message)
      runAfter:
        - generate-message
      taskRef:
        kind: Task
        name: curl
