apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-output-task
spec:
  results:
    - name: output
      description: "The output data"
  steps:
    - name: generate
      image: alpine
      script: |
        echo - name: url-secret
                  value: rocketchat-url
                - name: options
                  value:
                    - "-X"
                    - "POST"
                    - "-H"
                    - "Content-Type: application/json"
                    - "--data"
                    - |-
                      {
                        "text": "Automated Alert",
                        "attachments": [
                          {
                            "title": "App updated and Built",
                            "text": "Some intriguing text.",
                            "color": "#764FA5"
                          }
                        ]
                      } > /tekton/results/output