apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: start-build
spec:
  results:
    - description: Output of the start-build command
      name: build-output
      type: string
  steps:
    - args:
        - |
          oc start-build notify-bc --wait > $(results.build-output.path)
      command:
        - sh
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: start-build
      resources: {}